name: CD

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn
      - run: yarn build-ipfs
      - name: Upload to IPFS
        id: upload
        uses: aquiladev/ipfs-action@v0.1.3
        with:
          path: ./out
          service: pinata
          pinataKey: ${{ secrets.PINATA_API_KEY }}
          pinataSecret: ${{ secrets.PINATA_SECRET_API_KEY }}
      - run: node --experimental-modules update-dnslink.mjs
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          IPFS_HASH: ${{ steps.upload.outputs.hash }}
